# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
  'RCTGeolocation',
  'RCTNetwork'
  # Add any other subspecs you want to use in your project
]

pod 'RCTMapboxGL', :path => '../node_modules/@mapbox/react-native-mapbox-gl/ios'

target 'mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobile
  target 'mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
